### ISSUE TITLE
Account Create via Proxy

### ISSUE THREAD

**Issue by pavle93** [huttarichard/instagram-private-api-proxy#2]
Hi mate, thanks for the great library. However I have one question, couldn't get Account creation to work at all, and since I am still learning Nodejs, I'm a bit confused by the test examples you've provided. Here is what I  have done: 

`var server;
server = new ClientV1.Server("61.174.10.22", 8080);
ClientV1.Account.create(server, 'testistest111@mailinator.com', 'TestisProxy13337', 'proxy1337', 'Doesnt Matter');`

The code executes but returns an error:

> Unhandled rejection ParseError: Not possible to parse API response
Unhandled rejection UnknownResponseError: Something goes wrong

**Comment by huttarichard** [comment]
@pavle93 this library is dead.  You can use proxy option and something like squid proxy with https://github.com/huttarichard/instagram-private-api
